<?php echo $this->partial('_blocks/menu.phtml', array('my'=>1));?>
<div class="clear_fix"></div>
<div id="main">
    <div class="module_header">Авторы</div>
    <div class="clear_fix"></div>
    <div class="clear_fix"></div>
    <div class="clear_fix"></div>
    <div class="clear_fix"></div>
    <div uid="<?php echo $this->authors[0] ?>" class="mt8">
    </div>

    <div class="clear_fix"></div>
    <div id="vk_comments"></div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        Common.intentionViewUid('Author');
    })
    VK.Widgets.Comments("vk_comments", {limit: 5, width: "590", attach: "*", pageUrl:'<?php echo $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"]; ?>'});
</script>