<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="ru" xml:lang="ru">
<head>
    <title>Веришь не веришь</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="description" content="Веришь не веришь"/>
    <meta name="title" content="Веришь не веришь"/>
    <script src="http://vk.com/js/api/xd_connection.js?2" type="text/javascript"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <?php echo $this->headLink();?>
    <?php echo $this->headScript();?>

    <script type="text/javascript">
//google счетчик
    </script>
</head>
<body <?php if ($this->color):?> style="background-color: <?php echo $this->color;?>"<?php endif;?>>
<div id="header">

</div>
<div class="clear_fix"></div>
<div id="content">
    <?php echo $this->layout()->content; ?>
</div>
<div class="clear_fix"></div>
<div id="footer">

</div>
<div class="clear_fix"></div>
<script type="text/javascript" async>
    function setCookie (name, value, expires, path, domain, secure) {
        document.cookie = name + "=" + escape(value) +
                ((expires) ? "; expires=" + expires : "") +
                ((path) ? "; path=" + path : "") +
                ((domain) ? "; domain=" + domain : "") +
                ((secure) ? "; secure" : "");
    }

    if (self.parent.frames.length == 0) {
        setCookie('redirect', document.location.href, new Date(), '/');
        document.location.href = 'http://vk.com/app<?php echo $this->app_id;?>';
    }
    var windowHeight = 0;
    <?php if ($this->userId){ ?>
    Common.profileuser["uid"] = <?php echo $this->userId;?>;
        <?php } ?>
    VK.init(function(data) {
        $(document).ready(function() {
            setInterval(function(){
                var height = $('body').height() + 15;
                var width = $('html').width();
                if (height<500) {
                    height = 500;
                }
                if (height != windowHeight && height>=500) {
                    VK.callMethod("resizeWindow", width, height);
                    windowHeight = height;
                }
            }, 500);
        })
    });
</script>
</body>
</html>